In [ ]:
%matplotlib inline


Training GNN with Neighbor Sampling for Node Classification
===========================================================

This tutorial shows how to train a multi-layer GraphSAGE for node
classification on ``ogbn-arxiv`` provided by [Open Graph
Benchmark (OGB)](https://ogb.stanford.edu/). The dataset contains around
170 thousand nodes and 1 million edges.

By the end of this tutorial, you will be able to

-  Train a GNN model for node classification on a single GPU with DGL's
   neighbor sampling components.

This tutorial assumes that you have read the [Introduction of Neighbor
Sampling for GNN Training](L0_neighbor_sampling_overview.ipynb).


Loading Dataset
---------------

OGB already prepared the data as DGL graph.




In [1]:
import dgl
import torch
import numpy as np
from ogb.nodeproppred import DglNodePropPredDataset

dataset = DglNodePropPredDataset('ogbn-arxiv')
device = 'cpu'      # change to 'cuda' for GPU

Using backend: pytorch


Downloaded 0.08 GB: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]


Extracting dataset/arxiv.zip
Loading necessary files...
This might take a while.


100%|██████████| 1/1 [00:00<00:00, 138.45it/s]

Processing graphs...
Converting graphs into DGL objects...
Saving...


OGB dataset is a collection of graphs and their labels. ``ogbn-arxiv``
dataset only contains a single graph. So you can
simply get the graph and its node labels like this:




In [2]:
graph, node_labels = dataset[0]
# Add reverse edges since ogbn-arxiv is unidirectional.
graph = dgl.add_reverse_edges(graph)
graph.ndata['label'] = node_labels[:, 0]
print(graph)
print(node_labels)

node_features = graph.ndata['feat']
num_features = node_features.shape[1]
num_classes = (node_labels.max() + 1).item()
print('Number of classes:', num_classes)

Graph(num_nodes=169343, num_edges=2332486,
      ndata_schemes={'year': Scheme(shape=(1,), dtype=torch.int64), 'feat': Scheme(shape=(128,), dtype=torch.float32), 'label': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={})
tensor([[ 4],
        [ 5],
        [28],
        ...,
        [10],
        [ 4],
        [ 1]])
Number of classes: 40


You can get the training-validation-test split of the nodes with
``get_split_idx`` method.




In [3]:
idx_split = dataset.get_idx_split()
train_nids = idx_split['train']
valid_nids = idx_split['valid']
test_nids = idx_split['test']

How DGL Handles Computation Dependency
--------------------------------------

In the [previous tutorial](L0_neighbor_sampling_overview.ipynb), you
have seen that the computation dependency for message passing of a
single node can be described as a series of *message flow graphs* (MFG).

![](https://data.dgl.ai/tutorial/img/bipartite.gif)

Defining Neighbor Sampler and Data Loader in DGL
------------------------------------------------

DGL provides tools to iterate over the dataset in minibatches
while generating the computation dependencies to compute their outputs
with the MFGs above. For node classification, you can use
``dgl.dataloading.NodeDataLoader`` for iterating over the dataset.
It accepts a sampler object to control how to generate the computation
dependencies in the form of MFGs.  DGL provides
implementations of common sampling algorithms such as
``dgl.dataloading.MultiLayerNeighborSampler`` which randomly picks
a fixed number of neighbors for each node.

<div class="alert alert-info">
    
**Note**: To write your own neighbor sampler, please refer to [this user guide section](https://docs.dgl.ai/guide/minibatch-custom-sampler.html).
    
</div>

The syntax of ``dgl.dataloading.NodeDataLoader`` is mostly similar to a
PyTorch ``DataLoader``, with the addition that it needs a graph to
generate computation dependency from, a set of node IDs to iterate on,
and the neighbor sampler you defined.

Let’s say that each node will gather messages from 4 neighbors on each
layer. The code defining the data loader and neighbor sampler will look
like the following.




In [4]:
sampler = dgl.dataloading.MultiLayerNeighborSampler([4, 4])
train_dataloader = dgl.dataloading.NodeDataLoader(
    # The following arguments are specific to NodeDataLoader.
    graph,              # The graph
    train_nids,         # The node IDs to iterate over in minibatches
    sampler,            # The neighbor sampler
    device=device,      # Put the sampled MFGs on CPU or GPU
    # The following arguments are inherited from PyTorch DataLoader.
    batch_size=1024,    # Batch size
    shuffle=True,       # Whether to shuffle the nodes for every epoch
    drop_last=False,    # Whether to drop the last incomplete batch
    num_workers=0       # Number of sampler processes
)

You can iterate over the data loader and see what it yields.




In [5]:
input_nodes, output_nodes, mfgs = example_minibatch = next(iter(train_dataloader))
print(example_minibatch)
print("To compute {} nodes' outputs, we need {} nodes' input features".format(len(output_nodes), len(input_nodes)))

[tensor([ 72643, 115210, 163116,  ...,  79731,  55737, 106865]), tensor([ 72643, 115210, 163116,  ...,  81095, 102068,  71131]), [Block(num_src_nodes=12467, num_dst_nodes=4042, num_edges=14540), Block(num_src_nodes=4042, num_dst_nodes=1024, num_edges=3225)]]
To compute 1024 nodes' outputs, we need 12467 nodes' input features


``NodeDataLoader`` gives us three items per iteration.

-  An ID tensor for the input nodes, i.e., nodes whose input features
   are needed on the first GNN layer for this minibatch.
-  An ID tensor for the output nodes, i.e. nodes whose representations
   are to be computed.
-  A list of MFGs storing the computation dependencies
   for each GNN layer.




You can get the source and destination node IDs of the MFGs
and verify that the first few source nodes are always the same as the destination
nodes.  As we described in the [overview](L0_neighbor_sampling_overview.ipynb),
destination nodes' own features from the previous layer may also be necessary in
the computation of the new features.




In [6]:
mfg_0_src = mfgs[0].srcdata[dgl.NID]
mfg_0_dst = mfgs[0].dstdata[dgl.NID]
print(mfg_0_src)
print(mfg_0_dst)
print(torch.equal(mfg_0_src[:mfgs[0].num_dst_nodes()], mfg_0_dst))

tensor([ 72643, 115210, 163116,  ...,  79731,  55737, 106865])
tensor([ 72643, 115210, 163116,  ...,  60885, 107551, 153275])
True


Defining Model
--------------

Let’s consider training a 2-layer GraphSAGE with neighbor sampling. The
model can be written as follows:




In [7]:
import torch.nn as nn
import torch.nn.functional as F
from dgl.nn import SAGEConv

class Model(nn.Module):
    def __init__(self, in_feats, h_feats, num_classes):
        super(Model, self).__init__()
        self.conv1 = SAGEConv(in_feats, h_feats, aggregator_type='mean')
        self.conv2 = SAGEConv(h_feats, num_classes, aggregator_type='mean')
        self.h_feats = h_feats

    def forward(self, mfgs, x):
        # Lines that are changed are marked with an arrow: "<---"

        h_dst = x[:mfgs[0].num_dst_nodes()]  # <---
        h = self.conv1(mfgs[0], (x, h_dst))  # <---
        h = F.relu(h)
        h_dst = h[:mfgs[1].num_dst_nodes()]  # <---
        h = self.conv2(mfgs[1], (h, h_dst))  # <---
        return h

model = Model(num_features, 128, num_classes).to(device)

If you compare against the code in the
[introduction](1_introduction.ipynb), you will notice several
differences:

-  **DGL GNN layers on MFGs**. Instead of computing on the
   full graph:

   ```python
   h = self.conv1(g, x)
   ```

   you only compute on the sampled MFG:

   ```python
   h = self.conv1(mfgs[0], (x, h_dst))
   ```
   
   All DGL’s GNN modules support message passing on MFGs,
   where you supply a pair of features, one for source nodes and another
   for destination nodes.

-  **Feature slicing for self-dependency**. There are statements that
   perform slicing to obtain the previous-layer representation of the
    nodes:

   ```python
   h_dst = x[:mfgs[0].num_dst_nodes()]
   ```

   ``num_dst_nodes`` method works with MFGs, where it will
   return the number of destination nodes.

   Since the first few source nodes of the yielded MFG are
   always the same as the destination nodes, these statements obtain the
   representations of the destination nodes on the previous layer. They are
   then combined with neighbor aggregation in ``dgl.nn.SAGEConv`` layer.

<div class="alert alert-info">
    
**Note**: See the [custom message passing tutorial](L4_message_passing.ipynb) for more details on how to
   manipulate MFGs produced in this way, such as the usage
   of ``num_dst_nodes``.
    
    
</div>




Defining Training Loop
----------------------

The following initializes the model and defines the optimizer.




In [8]:
opt = torch.optim.Adam(model.parameters())

When computing the validation score for model selection, usually you can
also do neighbor sampling. To do that, you need to define another data
loader.




In [9]:
valid_dataloader = dgl.dataloading.NodeDataLoader(
    graph, valid_nids, sampler,
    batch_size=1024,
    shuffle=False,
    drop_last=False,
    num_workers=0,
    device=device
)

The following is a training loop that performs validation every epoch.
It also saves the model with the best validation accuracy into a file.




In [10]:
import tqdm
import sklearn.metrics

best_accuracy = 0
best_model_path = 'model.pt'
for epoch in range(10):
    model.train()

    with tqdm.tqdm(train_dataloader) as tq:
        for step, (input_nodes, output_nodes, mfgs) in enumerate(tq):
            # feature copy from CPU to GPU takes place here
            inputs = mfgs[0].srcdata['feat']
            labels = mfgs[-1].dstdata['label']

            predictions = model(mfgs, inputs)

            loss = F.cross_entropy(predictions, labels)
            opt.zero_grad()
            loss.backward()
            opt.step()

            accuracy = sklearn.metrics.accuracy_score(labels.cpu().numpy(), predictions.argmax(1).detach().cpu().numpy())

            tq.set_postfix({'loss': '%.03f' % loss.item(), 'acc': '%.03f' % accuracy}, refresh=False)

    model.eval()

    predictions = []
    labels = []
    with tqdm.tqdm(valid_dataloader) as tq, torch.no_grad():
        for input_nodes, output_nodes, mfgs in tq:
            inputs = mfgs[0].srcdata['feat']
            labels.append(mfgs[-1].dstdata['label'].cpu().numpy())
            predictions.append(model(mfgs, inputs).argmax(1).cpu().numpy())
        predictions = np.concatenate(predictions)
        labels = np.concatenate(labels)
        accuracy = sklearn.metrics.accuracy_score(labels, predictions)
        print('Epoch {} Validation Accuracy {}'.format(epoch, accuracy))
        if best_accuracy < accuracy:
            best_accuracy = accuracy
            torch.save(model.state_dict(), best_model_path)

  6%|▌         | 5/89 [00:00<00:01, 46.20it/s, loss=1.772, acc=0.538]

Epoch 0 Validation Accuracy 0.5395483069901674


  7%|▋         | 6/89 [00:00<00:01, 56.67it/s, loss=1.476, acc=0.573]

Epoch 1 Validation Accuracy 0.6097184469277492


  7%|▋         | 6/89 [00:00<00:01, 57.32it/s, loss=1.310, acc=0.616]

Epoch 2 Validation Accuracy 0.628443907513675


  7%|▋         | 6/89 [00:00<00:01, 57.25it/s, loss=1.274, acc=0.627]

Epoch 3 Validation Accuracy 0.639719453672942


  7%|▋         | 6/89 [00:00<00:01, 57.87it/s, loss=1.172, acc=0.651]

Epoch 4 Validation Accuracy 0.6398872445384073


  7%|▋         | 6/89 [00:00<00:01, 58.30it/s, loss=1.211, acc=0.637]

Epoch 5 Validation Accuracy 0.6510285580053022


  7%|▋         | 6/89 [00:00<00:01, 57.96it/s, loss=1.147, acc=0.646]

Epoch 6 Validation Accuracy 0.6522030940635591


  7%|▋         | 6/89 [00:00<00:01, 57.25it/s, loss=1.115, acc=0.664]

Epoch 7 Validation Accuracy 0.6567670056042149


  7%|▋         | 6/89 [00:00<00:01, 57.63it/s, loss=1.108, acc=0.678]

Epoch 8 Validation Accuracy 0.6638477801268499


100%|██████████| 30/30 [00:00<00:00, 81.51it/s]

Epoch 9 Validation Accuracy 0.6629417094533374


Conclusion
----------

In this tutorial, you have learned how to train a multi-layer GraphSAGE
with neighbor sampling.